version: "3.3"

services:
  idtm_frontend:
    image: nginx:1.15.3
    container_name: idtm_frontend
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ../frontend/dist/idtm/:/usr/share/nginx/html/frontend/idtm/:ro
    ports:
      - 80:80
    links:
      - idtm_backend
    depends_on:
      - idtm_backend

  idtm_backend:
    container_name: idtm_backend
    build:
      context: ./../backend/
      dockerfile: ./../docker/Dockerfile
    ports:
      - 8080:8080